# Generated by Django 2.0.4 on 2018-04-15 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Other', max_length=32, null=True, unique=True, verbose_name='type')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=32)),
                ('date_published', models.DateField(default=django.utils.timezone.now, verbose_name='date published')),
                ('discription', models.CharField(default='', max_length=128)),
                ('comment', models.CharField(default='', max_length=128)),
                ('summ', models.IntegerField(default=0, verbose_name='Sum')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='expenses',
            field=models.ManyToManyField(related_name='category', to='ExpenseApp.Expense'),
        ),
    ]
