# Generated by Django 2.0.4 on 2018-04-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0002_auto_20180415_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='expenses',
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ManyToManyField(related_name='expenses', related_query_name='expenses', to='ExpenseApp.Category'),
        ),
    ]
