# Generated by Django 2.0.4 on 2018-04-15 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0003_auto_20180415_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_published',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date'),
        ),
    ]
