# Generated by Django 2.0.4 on 2018-04-16 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0004_auto_20180416_0050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='discription',
            new_name='description',
        ),
    ]
