# Generated by Django 2.0.4 on 2018-04-16 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0005_auto_20180417_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='date_published',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='summ',
            new_name='price',
        ),
    ]
